In [1]:
import numpy as np

# Define the parity matrix H based on stabilizers
H = np.array([[1, 1, 1, 0, 0, 0, 1],
              [0, 0, 1, 0, 1, 1, 1],
              [0, 1, 1, 1, 0, 1, 0]])

In [2]:
def calculate_G(H):
    """
    Calculates the generator matrix G' from the parity check matrix H.
    :param H: Parity check matrix (numpy array)
    :return: G, the generator matrix
    """
    r, n = H.shape
    k = n - r  # The number of information bits

    # Extract columns that do not correspond to the identity matrix columns
    P = []
    for i, col in enumerate(H.T):
        if not (np.count_nonzero(col) == 1 and col.sum() == 1):
            P.append(col)

    P = np.array(P)  # Transpose P to have the correct shape

    # Create an identity matrix I of size k x k
    I = np.eye(k, dtype=int)

    # Concatenate I and P to form G
    G = np.concatenate((I, P), axis=1)

    return G.astype(int)

In [3]:
# Define the generator matrix G
G = calculate_G(H)
print(G)

[[1 0 0 0 1 0 1]
 [0 1 0 0 1 1 1]
 [0 0 1 0 0 1 1]
 [0 0 0 1 1 1 0]]
